export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGGING_SUCCESS = 'LOGGING_SUCCESS';
export const PASSWORD_ERROR = 'PASSWORD_ERROR';
export const EMAIL_ERROR = 'EMAIL_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
