export const FETCHING_PRODUCTS_SUCCESS = 'FETCHING_PRODUCTS_SUCCESS';
export const FETCHING_PRODUCTS_ERROR = 'FETCHING_PRODUCTS_ERROR';

export const UPDATING_PRODUCTS_REQUEST = 'UPDATING_PRODUCTS_REQUEST';
export const UPDATING_PRODUCTS_SUCCESS = 'UPDATING_PRODUCTS_SUCCESS';
export const UPDATING_PRODUCTS_ERROR = 'UPDATING_PRODUCTS_ERROR';

export const REFRESHING_PRODUCTS_REQUEST = 'REFRESHING_PRODUCTS_REQUEST';
