export const FETCHING_SHIPMENTS_REQUEST = 'FETCHING_SHIPMENTS_REQUEST';
export const FETCHING_SHIPMENTS_SUCCESS = 'FETCHING_SHIPMENTS_SUCCESS';
export const FETCHING_SHIPMENTS_ERROR = 'FETCHING_SHIPMENTS_ERROR';

export const UPDATING_SHIPMENT_REQUEST = 'UPDATING_SHIPMENT_REQUEST';
export const UPDATING_SHIPMENT_SUCCESS = 'UPDATING_SHIPMENT_SUCCESS';
export const UPDATING_SHIPMENT_ERROR = 'UPDATING_SHIPMENT_ERROR';

export const REFRESHING_SHIPMENT_REQUEST = 'REFRESHING_SHIPMENT_REQUEST';
